<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-FR81P7PN" name="com.testng.concepts.TimeOutTest" tests="2" failures="0" timestamp="2021-03-01T17:26:04 IST" time="1.546" errors="1">
  <testcase name="searchMobile" time="1.008" classname="com.testng.concepts.TimeOutTest"/>
  <testcase name="searchLaptop" time="0.538" classname="com.testng.concepts.TimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.concepts.TimeOutTest.searchLaptop() didn&#039;t finish within the time-out 400">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.concepts.TimeOutTest.searchLaptop() didn't finish within the time-out 400
at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- searchLaptop -->
</testsuite> <!-- com.testng.concepts.TimeOutTest -->
